name: Build and push container images

on:
  push:
    branches:
    - main
    tags:
    - '[0-9]*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Git repository
      uses: actions/checkout@v3

    - name: Set tags
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          hub.opensciencegrid.org/opensciencegrid/htcondor-file-transfer-ep
        tags: |
          type=ref,event=branch,pattern={{branch}}-docker
          type=ref,event=tag,pattern={{tag}}-docker
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}-docker,enable={{is_default_branch}}
          type=raw,value=latest-docker,enable={{is_default_branch}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into Hub
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
